name: GoTests

on: [push, workflow_dispatch]

jobs:
  raffle:
    name: go-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'

      - name: Test
        run: go test -mod=mod ...
